unset_all = true
keep = [
    'APPIMAGE_EXTRACT_AND_RUN',
    'APPIMAGE_EXTRACT_DIR',

    'USER',
    'HOME',
    'PATH',

    'LANG',
    'LANGUAGE',
    'TERM',
    'COLORTERM',

    'WAYLAND_DISPLAY',
    'DISPLAY',

    'XDG_SESSION_TYPE',
    'XDG_SESSION_DESKTOP',
    'XDG_CURRENT_DESKTOP',

    'XDG_RUNTIME_DIR',
    'DBUS_SESSION_BUS_ADDRESS',
    'XDG_CONFIG_HOME',
    'XDG_DATA_HOME',
    'XDG_CACHE_HOME',
    'XDG_STATE_HOME',

    'XCURSOR_THEME',
    'XCURSOR_SIZE',
    'HYPRCURSOR_SIZE',

    'MOZ_ENABLE_WAYLAND',
    'QT_QPA_PLATFORM',
    'QT_QPA_PLATFORMTHEME',
    'QT_WAYLAND_DISABLE_WINDOWDECORATION',
    'ELECTRON_OZONE_PLATFORM_HINT',
    '_JAVA_AWT_WM_NONREPARENTING',
]
